"""New Migration

Revision ID: 21b18749e72d
Revises: 428026291f0c
Create Date: 2021-09-27 12:45:02.373995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b18749e72d'
down_revision = '428026291f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
