"""New Migration

Revision ID: 3fea537c86d8
Revises: 
Create Date: 2021-09-29 11:24:45.564779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fea537c86d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_table',
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('evaluation', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('checksum', 'url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_table')
    # ### end Alembic commands ###
