"""New Migration

Revision ID: 428026291f0c
Revises: e9e74052322a
Create Date: 2021-09-27 12:30:21.672413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428026291f0c'
down_revision = 'e9e74052322a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
