"""New Migration

Revision ID: 4af95ef20473
Revises: 5e9926eb90b4
Create Date: 2021-09-24 09:19:54.867771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af95ef20473'
down_revision = '5e9926eb90b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
