"""New Migration

Revision ID: 5e9926eb90b4
Revises: 96e96538df0d
Create Date: 2021-09-24 08:47:18.614391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e9926eb90b4'
down_revision = '96e96538df0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_table', sa.Column('hash', sa.String(), nullable=True))
    op.add_column('dataset_table', sa.Column('url', sa.String(), nullable=True))
    op.add_column('dataset_table', sa.Column('evaluation', sa.String(), nullable=True))
    op.drop_column('dataset_table', 'name')
    op.drop_column('dataset_table', 'testProperty')
    op.drop_column('dataset_table', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_table', sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dataset_table', sa.Column('testProperty', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dataset_table', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dataset_table', 'evaluation')
    op.drop_column('dataset_table', 'url')
    op.drop_column('dataset_table', 'hash')
    # ### end Alembic commands ###
