"""New Migration

Revision ID: aa3a36bf30f8
Revises: 9ad7f674357b
Create Date: 2021-10-27 13:48:33.233905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3a36bf30f8'
down_revision = '9ad7f674357b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
