"""New Migration

Revision ID: e9e74052322a
Revises: 4af95ef20473
Create Date: 2021-09-27 12:29:43.289455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e74052322a'
down_revision = '4af95ef20473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_table', sa.Column('checksum', sa.String(), nullable=True))
    op.drop_column('dataset_table', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_table', sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dataset_table', 'checksum')
    # ### end Alembic commands ###
