"""New Migration

Revision ID: f4f72affbbcc
Revises: 21b18749e72d
Create Date: 2021-09-27 13:07:38.725014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f72affbbcc'
down_revision = '21b18749e72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
