name: docker-compose-actions-workflow

on:
  pull_request:
    branches:
      - master
      - develop
  
jobs:
  docker:
    name: Docker testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Test API
        run: docker-compose exec api_service pytest .

      - name: Stop containers
        run: docker-compose down
